#ifndef _SHADERS_H
#define _SHADERS_H

/*Thanks to the twokings tutorial for this one*/
const char* vertexshade = "// Vertex shader input structure\n"
"struct VS_INPUT\n"
"{\n"
"    float4 Position   : POSITION;\n"
"    float4 Color    : COLOR0;\n"
"};\n"
"\n"
"\n"
"// Vertex shader output structure\n"
"struct VS_OUTPUT\n"
"{\n"
"    float4 Position   : POSITION;\n"
"    float4 Color    : COLOR0;\n"
"};\n"
"\n"
"\n"
"// Global variables\n"
"float4x4 WorldViewProj;\n"
"\n"
"\n"
"// Name: Simple Vertex Shader\n"
"// Type: Vertex shader\n"
"// Desc: Vertex transformation and texture coord pass-through\n"
"//\n"
"VS_OUTPUT vs_main( in VS_INPUT In )\n"
"{\n"
"    VS_OUTPUT Out;                      //create an output vertex\n"
"\n"
"    Out.Position = mul(In.Position,\n"
"                       WorldViewProj);  //apply vertex transformation\n"
"    Out.Color  = In.Color;          //copy original texcoords\n"
"\n"
"    return Out;                         //return output vertex\n"
"}\n";
#endif